CONFIG_LOG=y
CONFIG_LOG_DEFAULT_LEVEL=3
CONFIG_LOG_MODE_DEFERRED=y
CONFIG_LOG_RATELIMIT=y
CONFIG_LOG_RATELIMIT_INTERVAL_MS=1000

CONFIG_THREAD_NAME=y
CONFIG_THREAD_MONITOR=y

CONFIG_SHELL=y
CONFIG_KERNEL_SHELL=y
CONFIG_SHELL_LOG_BACKEND=n
# Defaults to n when the serial shell is enabled
CONFIG_LOG_BACKEND_UART=y

CONFIG_INIT_STACKS=y
CONFIG_THREAD_STACK_INFO=y

CONFIG_CONSOLE=y

CONFIG_TRACING=y
CONFIG_TRACING_CTF=y
CONFIG_TRACING_SYNC=y
CONFIG_TRACING_BACKEND_UART=y
CONFIG_TRACING_PACKET_MAX_SIZE=64
# Capture uart1 (tracing UART) to build/channel0_0
CONFIG_QEMU_EXTRA_FLAGS="-serial file:channel0_0"

CONFIG_MAIN_STACK_SIZE=2048

CONFIG_LOG_RATELIMIT=y
CONFIG_LOG_RATELIMIT_INTERVAL_MS=1000